### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by PiotrPardo** [MyPureCloud/terraform-provider-genesyscloud#234]
Hi,

I'm receiving strange error when I want to add new schedule group.
```

22:28:07  [31mâ•µ[0m[0m
22:28:07  [31mâ•·[0m[0m
22:28:07  [31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0m[0m  with genesyscloud_architect_schedules.CsInServiceWeek,
22:28:07  [31mâ”‚[0m [0m  on genesyscloud_architect_schedules.tf line 439, in resource "genesyscloud_architect_schedules" "CsInServiceWeek":
22:28:07  [31mâ”‚[0m [0m 439: resource "genesyscloud_architect_schedules" "CsInServiceWeek" [4m{[0m[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0mThe plugin encountered an error, and failed to respond to the
22:28:07  [31mâ”‚[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
22:28:07  [31mâ”‚[0m [0mcontain more details.
22:28:07  [31mâ•µ[0m[0m
22:28:07  [31mâ•·[0m[0m
22:28:07  [31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0m[0m  with genesyscloud_architect_schedules.ErmInServiceWeek,
22:28:07  [31mâ”‚[0m [0m  on genesyscloud_architect_schedules.tf line 516, in resource "genesyscloud_architect_schedules" "ErmInServiceWeek":
22:28:07  [31mâ”‚[0m [0m 516: resource "genesyscloud_architect_schedules" "ErmInServiceWeek" [4m{[0m[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0mThe plugin encountered an error, and failed to respond to the
22:28:07  [31mâ”‚[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
22:28:07  [31mâ”‚[0m [0mcontain more details.
22:28:07  [31mâ•µ[0m[0m
22:28:07  [31mâ•·[0m[0m
22:28:07  [31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0m[0m  with genesyscloud_architect_schedules.raceInServiceWeek,
22:28:07  [31mâ”‚[0m [0m  on genesyscloud_architect_schedules.tf line 530, in resource "genesyscloud_architect_schedules" "raceInServiceWeek":
22:28:07  [31mâ”‚[0m [0m 530: resource "genesyscloud_architect_schedules" "raceInServiceWeek" [4m{[0m[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0mThe plugin encountered an error, and failed to respond to the
22:28:07  [31mâ”‚[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
22:28:07  [31mâ”‚[0m [0mcontain more details.
22:28:07  [31mâ•µ[0m[0m
22:28:07  [31mâ•·[0m[0m
22:28:07  [31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0m[0m  with genesyscloud_auth_role.SatManager,
22:28:07  [31mâ”‚[0m [0m  on genesyscloud_auth_role.tf line 443, in resource "genesyscloud_auth_role" "SatManager":
22:28:07  [31mâ”‚[0m [0m 443: resource "genesyscloud_auth_role" "SatManager" [4m{[0m[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0mThe plugin encountered an error, and failed to respond to the
22:28:07  [31mâ”‚[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
22:28:07  [31mâ”‚[0m [0mcontain more details.
22:28:07  [31mâ•µ[0m[0m
22:28:07  [31mâ•·[0m[0m
22:28:07  [31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0m[0m  with genesyscloud_auth_role.TrafficControll,
22:28:07  [31mâ”‚[0m [0m  on genesyscloud_auth_role.tf line 679, in resource "genesyscloud_auth_role" "TrafficControll":
22:28:07  [31mâ”‚[0m [0m 679: resource "genesyscloud_auth_role" "TrafficControll" [4m{[0m[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0mThe plugin encountered an error, and failed to respond to the
22:28:07  [31mâ”‚[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
22:28:07  [31mâ”‚[0m [0mcontain more details.
22:28:07  [31mâ•µ[0m[0m
22:28:07  [31mâ•·[0m[0m
22:28:07  [31mâ”‚[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0m[0m  with genesyscloud_auth_role.Telephony,
22:28:07  [31mâ”‚[0m [0m  on genesyscloud_auth_role.tf line 884, in resource "genesyscloud_auth_role" "Telephony":
22:28:07  [31mâ”‚[0m [0m 884: resource "genesyscloud_auth_role" "Telephony" [4m{[0m[0m
22:28:07  [31mâ”‚[0m [0m
22:28:07  [31mâ”‚[0m [0mThe plugin encountered an error, and failed to respond to the
22:28:07  [31mâ”‚[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
22:28:07  [31mâ”‚[0m [0mcontain more details.
22:28:07  [31mâ•µ[0m[0m
22:28:07  
22:28:07  Stack trace from the terraform-provider-genesyscloud_v0.14.1.exe plugin:
22:28:07  
22:28:07  panic: runtime error: invalid memory address or nil pointer dereference
22:28:07  [signal 0xc0000005 code=0x0 addr=0x8 pc=0x20fe209]
22:28:07  
22:28:07  goroutine 3700 [running]:
22:28:07  github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.createArchitectScheduleGroups(0x2949380, 0xc000cee1e0, 0xc00109e900, 0x2275f80, 0xc0007f1680, 0x0, 0xc000cee1f0, 0x2769270)
22:28:07  	github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_architect_schedulegroups.go:122 +0x409
22:28:07  github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.runWithPooledClient.func1(0x2949380, 0xc000cee1e0, 0xc00109e900, 0x2275f80, 0xc0007f10b0, 0x0, 0x0, 0x0)
22:28:07  	github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/sdk_client_pool.go:112 +0x27f
22:28:07  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00009e9a0, 0x2949300, 0xc00074d280, 0xc00109e900, 0x2275f80, 0xc0007f10b0, 0x0, 0x0, 0x0)
22:28:07  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:330 +0x184
22:28:07  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00009e9a0, 0x2949300, 0xc00074d280, 0xc000807520, 0xc00109e780, 0x2275f80, 0xc0007f10b0, 0x0, 0x0, 0x0, ...)
22:28:07  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:456 +0x67b
22:28:07  github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00008b2e0, 0x2949300, 0xc00074d280, 0xc0006bed70, 0xc00074d280, 0x0, 0x295a700)
22:28:07  	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xaef
22:28:07  github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0008605a0, 0x2949300, 0xc00074d280, 0xc0007552d0, 0xc0008605a0, 0xc0007f05a0, 0xc000bddba0)
22:28:07  	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb8
22:28:07  github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x24dc4e0, 0xc0008605a0, 0x29493c0, 0xc0007f05a0, 0xc0009ffd40, 0x0, 0x29493c0, 0xc0007f05a0, 0xc0002ea000, 0x1d7)
22:28:07  	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
22:28:07  google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b1dc0, 0x2956a80, 0xc000084780, 0xc000585680, 0xc0007229f0, 0x319e120, 0x0, 0x0, 0x0)
22:28:07  	google.golang.org/grpc@v1.37.0/server.go:1217 +0x522
22:28:07  google.golang.org/grpc.(*Server).handleStream(0xc0000b1dc0, 0x2956a80, 0xc000084780, 0xc000585680, 0x0)
22:28:07  	google.golang.org/grpc@v1.37.0/server.go:1540 +0xd25
22:28:07  google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003cd100, 0xc0000b1dc0, 0x2956a80, 0xc000084780, 0xc000585680)
22:28:07  	google.golang.org/grpc@v1.37.0/server.go:878 +0xa8
22:28:07  created by google.golang.org/grpc.(*Server).serveStreams.func1
22:28:07  	google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
22:28:07  
22:28:07  Error: The terraform-provider-genesyscloud_v0.14.1.exe plugin crashed!
22:28:07  
22:28:07  This is always indicative of a bug within the plugin. It would be immensely
22:28:07  helpful if you could report the crash with the plugin's maintainers so that it
22:28:07  can be fixed. The output above should help diagnose the issue.
```

What worries me is the fact that those object from logs are not related with schedule group I was trying to add. 

Did you had problem similar issue to that? Do you know how to solve it?

**Comment by ronanwatkins** [comment]
Hi,

What version of the provider are you using? The latest is `v1.1.3`. The crash log indicates an issue on line 122 of [resource_genesyscloud_architect_schedulegroups.go](https://github.com/MyPureCloud/terraform-provider-genesyscloud/blob/main/genesyscloud/resource_genesyscloud_architect_schedulegroups.go#L122) but there is nothing there so I think it's a bug that has been fixed in the latest version.

**Comment by PiotrPardo** [comment]
Hi,

Yes, I was using older version of provider. Thank you very much.
