### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by fraserc182** [MyPureCloud/terraform-provider-genesyscloud#77]
Hi,

I am trying to use the export resource to get a .json of my current dev genesys cloud environment.
I am using TF v1.0.1
When doing this I got the following error:

```
genesyscloud_tf_export.export: Creating...
╷
│ Error: Plugin did not respond
│
│   with genesyscloud_tf_export.export,
│   on main.tf line 16, in resource "genesyscloud_tf_export" "export":
│   16: resource "genesyscloud_tf_export" "export" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-genesyscloud_v0.11.1.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x11feb9b]

goroutine 625 [running]:
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.readIntegrationAction(0x18b72a0, 0xc0009181e0, 0xc000ae4100, 0x12e0180, 0xc00045d6b0, 0x0, 0xc0009181f0, 0x16ee748)
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_integration_action.go:245 +0xb3b
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.runWithPooledClient.func1(0x18b72a0, 0xc0009181e0, 0xc000ae4100, 0x12e0180, 0xc0004996b0, 0x0, 0x0, 0x0)
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/sdk_client_pool.go:112 +0x27f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000331c00, 0x18b7220, 0xc000697640, 0xc000ae4100, 0x12e0180, 0xc0004996b0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x187
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000331c00, 0x18b7220, 0xc000697640, 0xc0001b00e0, 0x12e0180, 0xc0004996b0, 0x1, 0x1, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:624 +0x1cb
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.getResourceState(0x18b7220, 0xc000697640, 0xc000331c00, 0xc000795b80, 0x18, 0xc0009746e0, 0x12e0180, 0xc0004996b0, 0x1, 0x0, ...)
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_tf_export.go:342 +0x107
github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.getResourcesForType.func1(0xc0008992d0, 0x18b7220, 0xc000697640, 0xc000331c00, 0x12e0180, 0xc0004996b0, 0xc000461920, 0x157173f, 0x1f, 0xc0006cdb20, ...)    
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_tf_export.go:282 +0xf8
created by github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud.getResourcesForType
        github.com/mypurecloud/terraform-provider-genesyscloud/genesyscloud/resource_genesyscloud_tf_export.go:277 +0x375

Error: The terraform-provider-genesyscloud_v0.11.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue
```

**Comment by joefruland** [comment]
This looks like the API returned an action with a null `integrationId` attribute. I'm not sure how that was configured in the system since that is a required attribute, but I will add a check for this.

**Comment by fraserc182** [comment]
@joefruland thanks for looking at this for me.
When you say it's a required attribute, is this something I can fix somewhere in the meantime?

**Comment by joefruland** [comment]
The error doesn't show which one, but it appears at least one of your integration actions is not configured with an associated integration ID. You could use this API to get all actions and look for one that is returning a null or missing `integrationId` attribute and update or delete that action: https://developer.genesys.cloud/api/rest/v2/integrations/#get-api-v2-integrations-actions

I should be able to have a fix in today that will prevent the provider from crashing, but if you try to use the exported config it will require you to manually set that attribute on the action (or remove it entirely).

**Comment by fraserc182** [comment]
Ah thanks for explaining, I'll give it a go. If not, I'll just wait for your fix. Thanks again.
